{"uuid": "a376ac4c-8098-421c-8326-e1f792118660", "children": ["c091d888-0018-4fa6-a4d0-5ae746b44672"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './data/login.yaml'\n", "trace": "  File \"D:\\Users\\tn_chenghao.yan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Users\\tn_chenghao.yan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Users\\tn_chenghao.yan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\tn_chenghao.yan\\PycharmProjects\\pythonProject\\test_request\\testcase\\test_popular.py\", line 26, in login\n    data=yaml_conf.yaml_load(\"./data/login.yaml\")\n  File \"C:\\Users\\tn_chenghao.yan\\PycharmProjects\\pythonProject\\test_request\\common\\yaml_conf.py\", line 9, in yaml_load\n    with open(yaml_path, \"r\", encoding=\"utf-8\") as f:\n"}, "start": 1639489210923, "stop": 1639489210924}], "start": 1639489210923, "stop": 1639489210936}