{"uuid": "e5033702-7f20-4e83-a415-e83c6a2fc3ff", "children": ["ef5f87bd-4b0b-4778-9138-d2b377ce5caf"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './data/login.yaml'\n", "trace": "  File \"D:\\Users\\tn_chenghao.yan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Users\\tn_chenghao.yan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Users\\tn_chenghao.yan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\tn_chenghao.yan\\PycharmProjects\\pythonProject\\test_request\\testcase\\test_popular.py\", line 26, in login\n    data=yaml_conf.yaml_load(\"./data/login.yaml\")\n  File \"C:\\Users\\tn_chenghao.yan\\PycharmProjects\\pythonProject\\test_request\\common\\yaml_conf.py\", line 9, in yaml_load\n    with open(yaml_path, \"r\", encoding=\"utf-8\") as f:\n"}, "start": 1639489210944, "stop": 1639489210945}], "start": 1639489210944, "stop": 1639489210960}