{"uuid": "5f915c48-fd7e-462c-9c8e-5dbe2e6e380d", "children": ["78204b7c-b265-4a76-aff7-dd6458e4fef9"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './data/login.yaml'\n", "trace": "  File \"D:\\Users\\tn_chenghao.yan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Users\\tn_chenghao.yan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Users\\tn_chenghao.yan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\tn_chenghao.yan\\PycharmProjects\\pythonProject\\test_request\\testcase\\test_popular.py\", line 26, in login\n    data=yaml_conf.yaml_load(\"./data/login.yaml\")\n  File \"C:\\Users\\tn_chenghao.yan\\PycharmProjects\\pythonProject\\test_request\\common\\yaml_conf.py\", line 9, in yaml_load\n    with open(yaml_path, \"r\", encoding=\"utf-8\") as f:\n"}, "start": 1639489210866, "stop": 1639489210866}], "start": 1639489210866, "stop": 1639489210878}